# Generated by Django 5.1.3 on 2024-11-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hash',
            field=models.TextField(default='default_hash'),
        ),
    ]
